### ISSUE TITLE
Co-locate Cypher import or move to dump files

### ISSUE THREAD

**Issue by fbiville** [neo4j-examples/movies-harness#32]
All downstream project CI pipelines currently download the movies dataset based on an old commit of the movies sandbox repository (github.com/neo4j-graph-examples/movies):

```yaml
      - name: Import dataset (Neo4j 3.5)
        if: ${{ startsWith(matrix.neo4j-version, '3.5') }}
        run: docker exec --interactive neo4j-e2e sh -c 'cat /movies/movies.cypher | cypher-shell -u neo4j -p abcde'
      - name: Import dataset
        if: ${{ !startsWith(matrix.neo4j-version, '3.5') }}
        run: docker exec --interactive neo4j-e2e cypher-shell -u neo4j -p abcde --file /movies/movies.cypher
```

We should at the very least add the Cypher files in this repo.
Otherwise, using dump files may be a good idea. That remains TBD.
